

DROP TABLE IF EXISTS topic;
CREATE TABLE topic (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, description VARCHAR(100) NOT NULL, PRIMARY KEY (id));

DROP TABLE IF EXISTS employee;
CREATE TABLE employee (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, age INT NOT NULL, PRIMARY KEY (id));

DROP TABLE IF EXISTS department;
CREATE TABLE department (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, description VARCHAR(100) NOT NULL, PRIMARY KEY (id));
